-- Introductions par livre (les 66), tirees du panorama de l'auteur
-- ("DECODER LA BIBLE") : ou on se situe, qui, pourquoi, le fil vers Christ,
-- et un verset-cle. Colonnes alignees sur ce qu'attend app/lire + Reader.

create table if not exists book_intros (
  book int primary key,           -- correspond a books.id (1-66)
  name text not null,
  title text not null,            -- titre memorable du livre
  section text not null,          -- groupe (Pentateuque, Prophetes majeurs...)
  testament text not null,        -- 'AT' | 'NT'
  situ text not null,             -- ou on se situe dans le fil
  who text not null,              -- qui
  why text not null,              -- pourquoi ce livre
  christ text not null,           -- le fil rouge vers Jesus
  key_verse text,                 -- verset-cle a ouvrir
  created_at timestamptz default now()
);

alter table book_intros enable row level security;
drop policy if exists pub_book_intros on book_intros;
create policy pub_book_intros on book_intros for select using (true);

insert into book_intros (book, name, title, section, testament, situ, who, why, christ, key_verse) values
(1, 'Genèse', 'La Lumière et les Origines', 'Le Pentateuque', 'AT', 'Tout au commencement : la création, la chute, le déluge, puis l''appel d''Abraham.', 'Moïse rassemble les récits des origines et des patriarches Abraham, Isaac, Jacob et Joseph.', 'Poser le socle de la foi : un Dieu relationnel qui crée par sa Parole, l''homme fait à son image, la rupture du péché, et la toute première promesse d''un Sauveur.', 'Dès la chute, Dieu annonce le Proto-Évangile : une descendance de la femme écrasera la tête du serpent.', 'Genèse 3.15'),
(2, 'Exode', 'La Libération par le Sang', 'Le Pentateuque', 'AT', 'Quatre siècles plus tard, les descendants d''Abraham sont esclaves en Égypte.', 'Moïse, appelé depuis le buisson ardent, conduit la sortie d''Égypte.', 'Montrer un Dieu qui entend le cri des opprimés, brise l''orgueil de Pharaon, sauve par le sang de l''agneau (la Pâque) et donne sa Loi.', 'L''agneau sans défaut dont le sang épargne de la mort est l''image parfaite de Christ, notre Pâque.', 'Exode 3.14'),
(3, 'Lévitique', 'Comment s''approcher du Dieu saint', 'Le Pentateuque', 'AT', 'Au pied du Sinaï, le peuple doit apprendre à vivre près d''un Dieu saint.', 'Moïse transmet le manuel des prêtres et des sacrifices.', 'Enseigner que le péché entraîne la mort et qu''un sacrifice innocent doit être offert à la place du coupable.', 'Tout le système sacrificiel est une pancarte de feu pointant vers l''Agneau de Dieu, le sacrifice définitif.', 'Lévitique 17.11'),
(4, 'Nombres', 'Le désert et l''ingratitude', 'Le Pentateuque', 'AT', 'Aux portes de la Terre promise, le peuple doute et se rebelle.', 'Moïse traverse quarante ans d''errance avec une génération incrédule.', 'Révéler la gravité de l''incrédulité et des murmures, mais aussi la grâce d''un Dieu qui nourrit chaque jour son peuple rebelle.', 'Le serpent de bronze élevé sur une perche, que Jésus citera en Jean 3, préfigure la croix qui guérit qui la regarde.', 'Nombres 6.24'),
(5, 'Deutéronome', 'Le Testament de Moïse', 'Le Pentateuque', 'AT', 'Les quarante ans s''achèvent ; une nouvelle génération va entrer dans le pays.', 'Moïse, vieux et sachant qu''il va mourir, livre son discours d''adieu.', 'Rappeler que Dieu a choisi son peuple par pur amour, et le placer devant le choix solennel de la vie ou de la mort.', '« L''homme ne vivra pas de pain seulement » : c''est le Deutéronome que Jésus opposera au tentateur.', 'Deutéronome 6.4'),
(6, 'Josué', 'La Conquête par la foi', 'Livres historiques', 'AT', 'Après le désert, le peuple entre enfin en Terre promise.', 'Josué, successeur de Moïse, conduit l''installation d''Israël.', 'Montrer un Dieu qui tient ses promesses : le Jourdain s''ouvre, Jéricho tombe au son des trompettes et de l''obéissance.', 'Josué (même nom que Yeshoua/Jésus) fait entrer le peuple dans le repos promis, ombre du repos que donne le Christ.', 'Josué 1.9'),
(7, 'Juges', 'Le cycle du chaos', 'Livres historiques', 'AT', 'La génération suivante oublie son Dieu et s''assimile aux nations.', 'Des « juges » comme Gédéon ou Samson sont suscités pour délivrer.', 'Décrire le cycle infernal : apostasie, oppression, cri de détresse, délivrance — et la profondeur du mal quand chacun fait ce qui lui semble bon.', 'L''échec répété des libérateurs humains fait soupirer après un Sauveur parfait et un vrai Roi.', 'Juges 21.25'),
(8, 'Ruth', 'Une lumière dans les ténèbres', 'Livres historiques', 'AT', 'Au cœur de la violence de l''époque des Juges brille un joyau de douceur.', 'Ruth, étrangère et veuve, et Boaz, l''homme au « droit de rachat ».', 'Montrer la fidélité et la providence de Dieu à travers une histoire d''amour et de rédemption.', 'Boaz, le proche-parent qui rachète, préfigure Christ notre Rédempteur ; Ruth deviendra l''arrière-grand-mère de David.', 'Ruth 1.16'),
(9, '1 Samuel', 'La royauté, de Saül à David', 'Livres historiques', 'AT', 'Israël réclame un roi humain pour être comme les autres nations.', 'Le prophète Samuel oint Saül, puis le jeune berger David.', 'Opposer l''orgueil de Saül au cœur repentant de David, et rappeler que Dieu regarde le cœur, non l''apparence.', 'David, le berger-roi selon le cœur de Dieu, annonce le grand Fils de David, le Messie.', '1 Samuel 16.7'),
(10, '2 Samuel', 'Le trône et la promesse', 'Livres historiques', 'AT', 'David est devenu roi et unifie la nation.', 'David, roi glorieux mais faillible, chute puis se repent.', 'Montrer la grandeur et les fautes de David, et surtout l''Alliance par laquelle Dieu lui promet un trône éternel.', 'La promesse d''un roi éternel issu de David est l''annonce directe du Christ.', '2 Samuel 7.16'),
(11, '1 Rois', 'La gloire et la division', 'Livres historiques', 'AT', 'Après David, Salomon bâtit le Temple, mais son cœur se corrompt.', 'Salomon, puis les rois d''un royaume déchiré, et le prophète Élie.', 'Montrer l''âge d''or, puis la rupture du royaume et la spirale de l''idolâtrie malgré les prophètes de feu.', 'Le Temple bâti par Salomon annonce le vrai Temple : le corps de Christ, où Dieu habite parmi les hommes.', '1 Rois 18.21'),
(12, '2 Rois', 'La descente vers l''exil', 'Livres historiques', 'AT', 'Les deux royaumes s''enfoncent dans l''idolâtrie.', 'Élisée et une longue succession de rois, jusqu''à la chute de Jérusalem.', 'Raconter la justice qui finit par tomber : Israël puis Juda déportés, le Temple brûlé.', 'L''exil montre que sans un cœur nouveau la Loi extérieure ne suffit pas — ce que la Nouvelle Alliance viendra accomplir.', '2 Rois 17.13'),
(13, '1 Chroniques', 'La mémoire de David', 'Livres historiques', 'AT', 'Après l''exil, le peuple relit son histoire pour retrouver son identité.', 'Un chroniqueur (tradition : Esdras) reprend les généalogies et le règne de David.', 'Réancrer le peuple dans ses racines et dans le culte, en centrant tout sur David et le Temple.', 'La lignée soigneusement conservée conduit jusqu''au Messie, fils de David.', '1 Chroniques 29.11'),
(14, '2 Chroniques', 'Le Temple et le réveil', 'Livres historiques', 'AT', 'L''histoire de Juda relue à la lumière du culte et des réformes.', 'Le chroniqueur retrace les rois de Juda, de Salomon à l''exil.', 'Rappeler que la fidélité au vrai culte relève une nation, et que l''humilité et la prière ramènent la bénédiction.', '« Si mon peuple s''humilie et prie... je guérirai son pays » : une promesse qui trouve sa plénitude en Christ.', '2 Chroniques 7.14'),
(15, 'Esdras', 'Le retour et la Parole', 'Livres historiques', 'AT', 'Soixante-dix ans après l''exil, les Perses autorisent le retour à Jérusalem.', 'Le prêtre Esdras restaure l''étude et la mise en pratique de la Loi.', 'Montrer un Dieu qui n''abandonne jamais : il ramène son peuple et rallume la faim de sa Parole.', 'La restauration du peuple et du culte prépare la scène de la venue du Sauveur.', 'Esdras 7.10'),
(16, 'Néhémie', 'Reconstruire les murailles', 'Livres historiques', 'AT', 'Jérusalem est en ruines et sans défense.', 'Néhémie, haut fonctionnaire, dirige la reconstruction des murailles.', 'Montrer la foi en action : une main sur la truelle, l''autre sur l''épée, face à l''hostilité des voisins.', '« La joie du Seigneur est votre force » : la reconstruction extérieure appelle la reconstruction intérieure qu''opère Christ.', 'Néhémie 8.10'),
(17, 'Esther', 'La providence cachée', 'Livres historiques', 'AT', 'En exil en Perse, les Juifs sont menacés d''extermination.', 'Esther, jeune orpheline devenue reine, risque sa vie pour son peuple.', 'Montrer que même quand le nom de Dieu n''est jamais prononcé, sa providence dirige souverainement l''histoire.', 'Le Dieu invisible qui sauve son peuple d''un complot mortel préfigure le salut accompli en secret à la croix.', 'Esther 4.14'),
(18, 'Job', 'Le mystère de la souffrance', 'Livres poétiques', 'AT', 'Un des plus anciens livres du monde, hors de la trame historique.', 'Job, homme droit et prospère, soudain frappé par le malheur.', 'Briser l''idée que la souffrance est toujours une punition, et enseigner la confiance dans un Dieu plus grand que notre intelligence.', '« Je sais que mon Rédempteur est vivant » : au fond de la nuit, Job entrevoit Celui qui se tiendra sur la terre.', 'Job 19.25'),
(19, 'Psaumes', 'Le miroir de l''âme', 'Livres poétiques', 'AT', 'Le recueil de prières et de chants d''Israël, traversant tous les siècles.', '150 poèmes, dont 73 attribués à David.', 'Autoriser l''âme à se présenter à Dieu sans filtre : cri, angoisse, repentance, louange cosmique.', 'Des psaumes comme le 22 décrivent la crucifixion mille ans à l''avance : mains percées, vêtements tirés au sort.', 'Psaumes 23.1'),
(20, 'Proverbes', 'L''école de la sagesse', 'Livres poétiques', 'AT', 'La sagesse pratique pour la vie de tous les jours.', 'Attribué au roi Salomon, l''homme le plus sage de son temps.', 'Donner des maximes tranchantes sur l''argent, le travail, la parole, l''amitié : l''intelligence est vaine sans la crainte de Dieu.', 'La Sagesse personnifiée qui était là dès l''origine annonce le Christ, sagesse de Dieu.', 'Proverbes 9.10'),
(21, 'Ecclésiaste', 'La vanité sous le soleil', 'Livres poétiques', 'AT', 'Un bilan d''une modernité déroutante sur le sens de la vie.', 'Salomon, qui a tout expérimenté : richesse, pouvoir, plaisirs, savoir.', 'Montrer que sans Dieu tout est « vanité et poursuite du vent » : la matière ne comble jamais l''âme.', 'Le vide de tout ce qui est « sous le soleil » creuse la soif de l''éternel que seul le Christ remplit.', 'Ecclésiaste 3.11'),
(22, 'Cantique des cantiques', 'Le chant de l''amour', 'Livres poétiques', 'AT', 'Un joyau inattendu au milieu des livres de sagesse.', 'Un roi et une bien-aimée, dans un poème d''amour et de mariage.', 'Célébrer la beauté de l''amour, de la fidélité et de la sexualité voulus par Dieu.', 'L''Église a toujours lu ici l''image de l''amour passionné du Christ (l''Époux) pour son Église (l''Épouse).', 'Cantique des cantiques 8.6'),
(23, 'Ésaïe', 'Le cinquième évangéliste', 'Prophètes majeurs', 'AT', 'Sept siècles avant Jésus, au temps où Juda flirte avec le jugement.', 'Le prophète Ésaïe, le plus magistral des prophètes.', 'Dénoncer le péché, puis faire exploser la grâce : l''annonce d''un enfant divin et d''un Serviteur souffrant.', 'Ésaïe 53 décrit la substitution de la croix — transpercé pour nos révoltes — sept siècles à l''avance.', 'Ésaïe 53.5'),
(24, 'Jérémie', 'Le prophète au cœur brisé', 'Prophètes majeurs', 'AT', 'Jérusalem s''entête dans le mal, à la veille de sa destruction.', 'Jérémie, « le prophète pleureur », rejeté et persécuté.', 'Avertir pendant quarante ans d''une destruction inévitable, sans jamais être écouté.', 'Au milieu des cendres, Jérémie reçoit la promesse de la Nouvelle Alliance : la Loi écrite dans les cœurs.', 'Jérémie 31.33'),
(25, 'Lamentations', 'Les larmes sur la ville', 'Prophètes majeurs', 'AT', 'Jérusalem vient d''être détruite ; tout semble perdu.', 'Jérémie pleure la ruine de sa ville bien-aimée.', 'Donner des mots à la douleur la plus absolue, sans nier l''espérance.', '« Les bontés du Seigneur se renouvellent chaque matin » : au fond du deuil brille la fidélité qui portera jusqu''à Christ.', 'Lamentations 3.22'),
(26, 'Ézéchiel', 'Les ossements desséchés', 'Prophètes majeurs', 'AT', 'Prêtre déporté à Babylone, loin du Temple détruit.', 'Ézéchiel, prophète des visions et des mises en scène chocs.', 'Annoncer, par la vision des os qui revivent, que Dieu ressuscitera un peuple mort et lui donnera un cœur de chair.', 'Le cœur nouveau et l''Esprit promis s''accomplissent par l''œuvre de Christ et le don de l''Esprit.', 'Ézéchiel 36.26'),
(27, 'Daniel', 'Le Fils de l''homme', 'Prophètes majeurs', 'AT', 'Jeune exilé, Daniel sert à la cour des rois païens.', 'Daniel et ses compagnons, fidèles jusque dans la fournaise et la fosse aux lions.', 'Montrer la fidélité sous la menace et dévoiler l''histoire des empires jusqu''au Royaume éternel.', 'Daniel voit venir « quelqu''un comme un fils d''homme » recevant un règne éternel : titre que Jésus s''appliquera.', 'Daniel 7.13'),
(28, 'Osée', 'L''amour scandaleux de Dieu', 'Prophètes mineurs', 'AT', 'Le royaume du Nord s''enfonce dans l''idolâtrie.', 'Osée, à qui Dieu ordonne d''épouser une femme infidèle.', 'Rendre visible, par un mariage brisé et racheté, à quel point l''idolâtrie blesse le cœur de Dieu.', 'Un Dieu qui rachète sans cesse son épouse adultère : c''est l''amour qui ira jusqu''à la croix.', 'Osée 2.21'),
(29, 'Joël', 'Le jour du Seigneur', 'Prophètes mineurs', 'AT', 'Une invasion de sauterelles ravage le pays comme un signe.', 'Le prophète Joël appelle à un jeûne et à un retour au Seigneur.', 'Appeler à la repentance sincère (« déchirez vos cœurs, non vos vêtements ») et annoncer l''effusion de l''Esprit.', '« Je répandrai mon Esprit sur toute chair » : Pierre citera Joël le jour de la Pentecôte.', 'Joël 2.28'),
(30, 'Amos', 'La justice comme un torrent', 'Prophètes mineurs', 'AT', 'Une époque de prospérité qui écrase les pauvres.', 'Amos, berger appelé à prophétiser contre les élites.', 'Dénoncer les cultes hypocrites de ceux qui prient bien mais oppriment le faible.', '« Que la justice coule comme de l''eau » : le vrai culte cherché par Dieu se révèle pleinement en Christ.', 'Amos 5.24'),
(31, 'Abdias', 'La chute de l''orgueil', 'Prophètes mineurs', 'AT', 'Édom s''est réjoui du malheur de son frère Jacob.', 'Abdias, auteur du plus court livre de l''Ancien Testament.', 'Annoncer que l''orgueil des nations hostiles au peuple de Dieu sera abattu.', '« La royauté appartiendra au Seigneur » : le jugement des orgueilleux prépare le règne du Roi.', 'Abdias 1.21'),
(32, 'Jonas', 'La grâce plus grande que nos frontières', 'Prophètes mineurs', 'AT', 'Dieu envoie son prophète chez l''ennemi honni.', 'Jonas, qui fuit plutôt que d''annoncer la grâce à Ninive.', 'Montrer que la grâce de Dieu pulvérise le nationalisme et s''étend même à nos pires ennemis.', 'Trois jours dans le poisson : Jésus en fera le signe de sa mort et de sa résurrection.', 'Jonas 4.2'),
(33, 'Michée', 'Le Sauveur de Bethléhem', 'Prophètes mineurs', 'AT', 'Face à l''injustice sociale et à la corruption religieuse.', 'Michée, contemporain d''Ésaïe.', 'Réclamer la justice, la bonté et l''humilité, et localiser d''avance la naissance du Messie.', '« Et toi, Bethléhem... de toi sortira celui qui gouvernera Israël » : la prophétie s''accomplit à Noël.', 'Michée 5.1'),
(34, 'Nahum', 'La fin de Ninive', 'Prophètes mineurs', 'AT', 'Un siècle après Jonas, Ninive est retombée dans la violence.', 'Le prophète Nahum annonce la chute de l''empire cruel.', 'Affirmer que Dieu est lent à la colère mais qu''il ne laisse pas le mal impuni.', 'La justice qui abat l''oppresseur console les opprimés et pointe vers le Juge final, le Christ.', 'Nahum 1.7'),
(35, 'Habacuc', 'Le juste vivra par la foi', 'Prophètes mineurs', 'AT', 'Le prophète est scandalisé que Dieu laisse le mal prospérer.', 'Habacuc, qui ose interroger Dieu et attend sa réponse.', 'Passer du « pourquoi ? » à la confiance : le salut ne vient pas de tout comprendre, mais de la fidélité à Dieu.', '« Le juste vivra par sa foi » : cette clé bouleversera Paul, Augustin et Luther, cœur de l''Évangile.', 'Habacuc 2.4'),
(36, 'Sophonie', 'Le jour du jugement et de la joie', 'Prophètes mineurs', 'AT', 'Juda est mûr pour le jugement, mais un reste sera sauvé.', 'Sophonie annonce le grand « jour du Seigneur ».', 'Avertir du jugement, puis promettre un Dieu qui se réjouit sur son peuple restauré.', '« Il exultera de joie à ton sujet » : la joie de Dieu sur les siens éclate dans le salut de Christ.', 'Sophonie 3.17'),
(37, 'Aggée', 'Rebâtir la maison de Dieu', 'Prophètes mineurs', 'AT', 'De retour d''exil, le peuple néglige la reconstruction du Temple.', 'Aggée secoue les rapatriés découragés.', 'Rappeler de donner à Dieu la première place plutôt qu''à son propre confort.', 'La gloire du second Temple dépassera celle du premier : car le Messie y entrera en personne.', 'Aggée 2.9'),
(38, 'Zacharie', 'Le Roi humble et transpercé', 'Prophètes mineurs', 'AT', 'Après l''exil, il faut raviver l''attente du Messie.', 'Zacharie, prophète aux visions saisissantes.', 'Consolider l''espérance par des annonces précises sur le Messie à venir.', 'Le Roi qui vient monté sur un âne, trahi pour trente pièces, le corps transpercé : tout se réalise en Jésus.', 'Zacharie 9.9'),
(39, 'Malachie', 'Le dernier appel avant le silence', 'Prophètes mineurs', 'AT', 'Dernier livre de l''Ancien Testament ; la ferveur s''est éteinte.', 'Malachie dénonce le cynisme religieux du peuple.', 'Réveiller un culte devenu routinier et annoncer un messager qui préparera le Seigneur.', 'Le messager promis est Jean-Baptiste ; puis le rideau tombe pour quatre siècles avant la venue du Fils.', 'Malachie 3.1'),
(40, 'Matthieu', 'Jésus, le Roi promis', 'Évangiles', 'NT', 'La longue attente s''achève : le Messie paraît.', 'Matthieu, percepteur d''impôts appelé par un seul mot : « Suis-moi ».', 'Prouver à un public juif, textes à l''appui, que Jésus est le descendant royal de David, le Messie attendu.', 'Le Sermon sur la montagne révèle le Royaume des cieux : il appartient aux cœurs brisés qui reconnaissent leur pauvreté.', 'Matthieu 5.3'),
(41, 'Marc', 'Jésus, le Serviteur en action', 'Évangiles', 'NT', 'Le récit brut et rapide de la mission de Jésus.', 'Jean-Marc, à partir des souvenirs de l''apôtre Pierre.', 'Montrer, pour un esprit romain pragmatique, un Jésus puissant qui affronte le mal — « aussitôt » revient sans cesse.', '« Le Fils de l''homme est venu pour servir et donner sa vie en rançon » : le sommet du service est la croix.', 'Marc 10.45'),
(42, 'Luc', 'Jésus, le Sauveur des exclus', 'Évangiles', 'NT', 'Une enquête méthodique sur la vie de Jésus.', 'Luc, médecin grec, seul auteur non-juif de la Bible.', 'Peindre la compassion absolue : femmes, enfants, pauvres, pécheurs sont le trésor du Royaume.', 'Seul Luc rapporte l''Enfant prodigue : un Père qui court vers le fils perdu — l''essence de la grâce.', 'Luc 19.10'),
(43, 'Jean', 'Jésus, le Fils de Dieu', 'Évangiles', 'NT', 'Non plus seulement l''histoire humaine, mais les profondeurs divines.', 'Jean, le disciple le plus proche de Jésus.', 'Prouver qui est vraiment Jésus, pour que le lecteur croie et ait la vie éternelle.', '« Au commencement était la Parole... et la Parole était Dieu » : les sept « Je suis » dévoilent sa divinité.', 'Jean 1.14'),
(44, 'Actes', 'Le feu de l''Esprit', 'Actes', 'NT', 'Jésus est monté au ciel ; les disciples attendent la promesse.', 'Luc écrit la « saison 2 » de son évangile ; Pierre puis Paul en sont les figures.', 'Raconter la naissance de l''Église : la Pentecôte, l''audace des témoins, l''Évangile qui franchit toutes les frontières.', 'L''ancien persécuteur Paul, foudroyé par le Christ vivant, devient le grand ambassadeur de la grâce jusqu''à Rome.', 'Actes 1.8'),
(45, 'Romains', 'Le chef-d''œuvre du salut', 'Épîtres de Paul', 'NT', 'Paul écrit à une église qu''il n''a pas fondée, la capitale de l''Empire.', 'L''apôtre Paul, au sommet de sa pensée.', 'Exposer méthodiquement l''Évangile : tous coupables, tous justifiés gratuitement par la foi en Christ.', 'La justification par la foi — la perfection de Jésus mise à notre compte — a provoqué les plus grands réveils de l''histoire.', 'Romains 3.23'),
(46, '1 Corinthiens', 'L''ordre et l''amour', 'Épîtres de Paul', 'NT', 'Une église douée mais désordonnée, dans une ville de débauche.', 'Paul recadre les Corinthiens avec fermeté et amour.', 'Répondre aux divisions, à l''immoralité et à l''orgueil spirituel, et remettre l''amour au centre de tout.', 'Le chapitre 13 sur l''amour : sans lui, tous nos exploits ne sont que du bruit — le cœur de la vie en Christ.', '1 Corinthiens 13.4'),
(47, '2 Corinthiens', 'La force dans la faiblesse', 'Épîtres de Paul', 'NT', 'Paul se défend contre ceux qui méprisent ses souffrances.', 'L''apôtre, intime et vulnérable, dévoile son cœur.', 'Montrer que Dieu ne cherche pas nos performances : sa puissance éclate à travers nos faiblesses assumées.', '« Ma grâce te suffit, ma puissance s''accomplit dans la faiblesse » : la vie chrétienne épouse la logique de la croix.', '2 Corinthiens 12.9'),
(48, 'Galates', 'La charte de la liberté', 'Épîtres de Paul', 'NT', 'De faux docteurs veulent rajouter la Loi au salut.', 'Paul, en colère, rédige le manifeste de la liberté chrétienne.', 'Défendre le salut par la seule grâce : ajouter une condition humaine, c''est vider la croix de son sens.', '« Ce n''est plus moi qui vis, c''est Christ qui vit en moi » : la liberté véritable, c''est Christ à la place de nos efforts.', 'Galates 2.20'),
(49, 'Éphésiens', 'Choisis avant la création', 'Épîtres de Paul', 'NT', 'Une des lettres écrites depuis la prison romaine.', 'Paul enchaîné, mais rempli de lumière.', 'Révéler que Dieu nous a choisis et adoptés par pur amour avant même la fondation du monde.', '« C''est par grâce que vous êtes sauvés, par la foi... c''est un don de Dieu » : rien ne vient de nos œuvres.', 'Éphésiens 2.8'),
(50, 'Philippiens', 'La joie incorruptible', 'Épîtres de Paul', 'NT', 'Paul écrit depuis sa cellule, en attente de jugement.', 'L''apôtre, sans une trace d''amertume.', 'Enseigner une joie qui ne dépend pas des circonstances, mais de l''union avec Christ.', '« Je peux tout par celui qui me fortifie » : la paix qui dépasse toute intelligence garde le cœur en Jésus.', 'Philippiens 4.13'),
(51, 'Colossiens', 'La suprématie du Christ', 'Épîtres de Paul', 'NT', 'Face à des philosophies qui rabaissent Jésus.', 'Paul écrit un poème sur la grandeur absolue du Christ.', 'Affirmer que Jésus est le Créateur et le maître de tout le visible et l''invisible.', '« Image du Dieu invisible... tout a été créé par lui et pour lui » : à la croix, il a désarmé toutes les puissances.', 'Colossiens 1.15'),
(52, '1 Thessaloniciens', 'L''espérance du retour', 'Épîtres de Paul', 'NT', 'Une jeune église persécutée, inquiète pour ses morts.', 'Paul console des chrétiens dans la peur.', 'Affermir l''espérance : la mort n''est pas un trou noir, car Jésus reviendra et ressuscitera les siens.', '« Le Seigneur lui-même descendra du ciel » : la grande espérance chrétienne, c''est le retour du Christ.', '1 Thessaloniciens 4.16'),
(53, '2 Thessaloniciens', 'Tenir bon jusqu''au bout', 'Épîtres de Paul', 'NT', 'Des malentendus sur le retour du Seigneur troublent l''église.', 'Paul corrige et encourage à la persévérance.', 'Calmer l''agitation, dénoncer l''oisiveté et appeler à travailler paisiblement en attendant.', 'L''attente du Seigneur n''est pas une excuse pour rêver, mais un appel à vivre saintement en Christ.', '2 Thessaloniciens 3.16'),
(54, '1 Timothée', 'Le bon ordre de l''Église', 'Épîtres de Paul', 'NT', 'Paul passe le relais à un jeune responsable.', 'L''apôtre écrit à Timothée, son enfant dans la foi.', 'Donner des instructions pratiques sur les réunions, le choix de leaders intègres et la pureté du message.', '« Un seul médiateur entre Dieu et les hommes, Jésus-Christ » : tout le ministère protège cet Évangile.', '1 Timothée 2.5'),
(55, '2 Timothée', 'Le testament de Paul', 'Épîtres de Paul', 'NT', 'Paul sent la mort approcher dans sa cellule.', 'Les derniers mots de l''apôtre à Timothée.', 'Encourager à garder la foi, à ne pas avoir peur et à s''attacher aux Écritures.', '« Toute l''Écriture est inspirée de Dieu » : le vieux combattant remet le flambeau de la Parole.', '2 Timothée 3.16'),
(56, 'Tite', 'Une foi qui se voit', 'Épîtres de Paul', 'NT', 'Organiser de jeunes églises en Crète.', 'Paul instruit son collaborateur Tite.', 'Relier la saine doctrine à une vie belle et intègre : la grâce enseigne à vivre autrement.', 'La grâce qui sauve est aussi celle qui transforme et fait attendre « la bienheureuse espérance ».', 'Tite 2.11'),
(57, 'Philémon', 'Un frère, non plus un esclave', 'Épîtres de Paul', 'NT', 'Un esclave en fuite est devenu chrétien.', 'Paul écrit à Philémon au sujet d''Onésime.', 'Demander d''accueillir l''esclave fugitif comme un frère bien-aimé, à égalité devant Dieu.', 'L''Évangile brise les barrières sociales : en Christ, le maître et l''esclave sont frères.', 'Philémon 1.16'),
(58, 'Hébreux', 'Jésus supérieur à tout', 'Épîtres générales', 'NT', 'Des chrétiens juifs, épuisés, tentés de revenir en arrière.', 'Un auteur anonyme démontre la supériorité de Christ.', 'Prouver que Jésus est la réalité dont l''Ancien Testament n''était que l''ombre : un sacrifice « meilleur » et définitif.', 'Supérieur aux anges, à Moïse, aux prêtres : revenir en arrière serait insulter la croix parfaite.', 'Hébreux 4.12'),
(59, 'Jacques', 'La foi en action', 'Épîtres générales', 'NT', 'Certains utilisent la grâce comme excuse pour ne rien changer.', 'Jacques, le demi-frère de Jésus, devenu pilier de l''Église.', 'Fustiger l''hypocrisie : une foi authentique produit toujours des actes d''amour.', '« La foi sans les œuvres est morte » : la vraie foi qui sauve n''est jamais seule.', 'Jacques 2.17'),
(60, '1 Pierre', 'L''espérance dans le feu', 'Épîtres générales', 'NT', 'Des chrétiens traqués et martyrisés par l''Empire.', 'Pierre, l''impulsif devenu roc, écrit un manuel de survie.', 'Rappeler que la terre n''est pas notre patrie finale : la souffrance purifie l''or de la foi.', '« Race choisie, peuple appelé des ténèbres à l''admirable lumière » : l''identité du croyant en Christ.', '1 Pierre 2.9'),
(61, '2 Pierre', 'Contre les faux docteurs', 'Épîtres générales', 'NT', 'Des cyniques se moquent du retour de Jésus qui « tarde ».', 'Pierre met en garde une dernière fois.', 'Dénoncer les séducteurs et rappeler la patience de Dieu qui laisse le temps de la repentance.', '« Pour le Seigneur mille ans sont comme un jour » : il patiente pour que le plus grand nombre soit sauvé.', '2 Pierre 3.9'),
(62, '1 Jean', 'Dieu est lumière et amour', 'Épîtres générales', 'NT', 'De fausses doctrines s''infiltrent dans les églises.', 'L''apôtre Jean, très âgé, écrit comme un grand-père.', 'Rétablir l''équation : Dieu est Vérité et Dieu est Amour, indissociables ; et donner l''assurance du salut.', '« Celui qui a le Fils a la vie » : on peut savoir avec certitude qu''on est passé de la mort à la vie.', '1 Jean 4.8'),
(63, '2 Jean', 'Marcher dans la vérité', 'Épîtres générales', 'NT', 'Des trompeurs circulent d''église en église.', 'Jean écrit un court billet de vigilance.', 'Rappeler d''aimer en vérité et de ne pas ouvrir la porte à ceux qui nient le Christ venu en chair.', 'L''amour et la vérité vont ensemble : aimer, c''est marcher selon les commandements du Seigneur.', '2 Jean 1.6'),
(64, '3 Jean', 'L''hospitalité fraternelle', 'Épîtres générales', 'NT', 'Une querelle d''accueil dans une église locale.', 'Jean écrit à son ami Gaïus.', 'Encourager à soutenir les vrais serviteurs de la vérité et à imiter le bien, non le mal.', 'Servir humblement les frères, c''est œuvrer avec la vérité de l''Évangile.', '3 Jean 1.11'),
(65, 'Jude', 'Combattre pour la foi', 'Épîtres générales', 'NT', 'Des imposteurs transforment la grâce en excuse pour le mal.', 'Jude, un autre demi-frère de Jésus.', 'Lancer un appel percutant à défendre la foi transmise face aux séducteurs.', '« À celui qui peut vous garder de la chute » : c''est Dieu qui préserve, et à lui la gloire par Jésus-Christ.', 'Jude 1.24'),
(66, 'Apocalypse', 'Le triomphe du Roi', 'Prophétie', 'NT', 'Jean est exilé sur l''île-prison de Patmos ; le mal semble triompher.', 'L''apôtre Jean reçoit le grand dévoilement.', 'Non pas terroriser, mais encourager : à travers les jugements, Dieu gagne à la fin.', 'Le Christ revient en Roi des rois ; la mort est engloutie, l''Éden retrouvé, Dieu habite parmi les siens pour toujours.', 'Apocalypse 21.4')
on conflict (book) do update set
  name = excluded.name, title = excluded.title, section = excluded.section,
  testament = excluded.testament, situ = excluded.situ, who = excluded.who,
  why = excluded.why, christ = excluded.christ, key_verse = excluded.key_verse;
