-- Base des mots importants (hebreu / arameen / grec), tiree des livrets
-- de Mickael A. : Noms de Dieu, Vocabulaire du croyant, Grands concepts.
create table if not exists bible_words (
  slug text primary key,
  term text,
  translit text not null,
  lang text not null,
  gloss text not null,
  theme text not null,
  sense text not null,
  christ text,
  refs text[] not null default '{}',
  created_at timestamptz not null default now()
);
alter table bible_words enable row level security;
drop policy if exists bible_words_read on bible_words;
create policy bible_words_read on bible_words for select using (true);

insert into bible_words (slug, term, translit, lang, gloss, theme, sense, christ, refs) values
('yahweh','יהוה','YHWH (Yahweh)','hébreu','Le Seigneur, « Je suis »','Noms de Dieu','Le Nom personnel de Dieu, révélé à Moïse au buisson ardent. Formé du verbe hayah (être, exister, devenir), il dit un Dieu qui existe par lui-même, de toute éternité, sans commencement ni fin. Si saint que les Juifs ne le prononcent pas, lui substituant Adonaï.','En Jean 8.58, Jésus dit : « Avant qu''Abraham fût, JE SUIS » — il prend pour lui le Nom divin. Ses sept « Je suis » en dévoilent les facettes.',array['Exode 3.14','Jean 8.58']::text[]),
('elohim','אֱלֹהִים','Elohim','hébreu','Dieu, le Créateur souverain','Noms de Dieu','Premier nom de Dieu dans la Bible. Pluriel de majesté de El : non pas plusieurs dieux, mais la plénitude infinie de la nature divine. Il dit la toute-puissance créatrice : Dieu parle, et les choses existent.','Jean 1.1-3 : tout a été créé par le Verbe, le Christ. Elohim a un visage, celui de Jésus (Colossiens 1.16).',array['Genèse 1.1','Colossiens 1.16']::text[]),
('adonai','אֲדֹנָי','Adonaï','hébreu','Seigneur, mon Maître','Noms de Dieu','Pluriel de majesté de Adon (seigneur, maître, propriétaire). Dire « Adonaï », c''est renoncer à être le maître de sa propre vie et s''abandonner avec confiance à un Seigneur bon et sage.','En Philippiens 2.9-11, tout genou fléchit devant Jésus proclamé Kyrios (Seigneur), traduction grecque exacte d''Adonaï.',array['Ésaïe 6.1','Philippiens 2.9-11']::text[]),
('el-shaddai','אֵל שַׁדַּי','El Shaddaï','hébreu','Dieu Tout-Puissant et nourricier','Noms de Dieu','Le Dieu « qui suffit ». La racine évoque à la fois shadad (être puissant) et shad (le sein nourricier) : une force qui protège et une tendresse qui nourrit. Révélé à Abraham centenaire, sans enfant.','La puissance qui suffit à tout s''accomplit en Christ « en qui habite corporellement toute la plénitude de la divinité ».',array['Genèse 17.1','2 Corinthiens 12.9']::text[]),
('yahweh-rapha','יְהוָה רָפָא','Yahweh Rapha','hébreu','Le Seigneur qui guérit','Noms de Dieu','Le Dieu réparateur des âmes et des corps. Rapha, c''est raccommoder, restaurer, rendre entier ce qui était brisé.','Jésus guérit les malades et, par ses meurtrissures, guérit nos âmes (Ésaïe 53.5 ; 1 Pierre 2.24).',array['Exode 15.26','1 Pierre 2.24']::text[]),
('yahweh-jireh','יְהוָה יִרְאֶה','Yahweh Jireh','hébreu','Le Seigneur pourvoit','Noms de Dieu','Litt. « le Seigneur voit » et donc prépare d''avance. Nom donné par Abraham quand Dieu fournit un bélier à la place d''Isaac sur le mont Moriah.','Sur cette même montagne, Dieu pourvoira l''Agneau définitif : son propre Fils, à la place du pécheur.',array['Genèse 22.14','Romains 8.32']::text[]),
('yahweh-shalom','יְהוָה שָׁלוֹם','Yahweh Shalom','hébreu','Le Seigneur est paix','Noms de Dieu','Le Dieu qui donne le shalom : non l''absence de conflit, mais la plénitude, la santé, l''harmonie totale. Nom donné par Gédéon.','Jésus est « notre paix » (Éphésiens 2.14) et laisse aux siens sa paix, que le monde ne peut donner (Jean 14.27).',array['Juges 6.24','Jean 14.27']::text[]),
('yahweh-nissi','יְהוָה נִסִּי','Yahweh Nissi','hébreu','Le Seigneur ma bannière','Noms de Dieu','Le Dieu qui est ma victoire, l''étendard sous lequel on combat. Nom donné par Moïse après la victoire sur Amalek.','La vraie victoire est remportée à la croix, où Christ a désarmé les puissances (Colossiens 2.15).',array['Exode 17.15','Colossiens 2.15']::text[]),
('yahweh-sabaoth','יְהוָה צְבָאוֹת','Yahweh Sabaoth','hébreu','Le Seigneur des armées','Noms de Dieu','Le Dieu qui commande les armées du ciel et combat pour son peuple. Le titre du Roi guerrier et souverain.','Le Seigneur des armées est le même qui revient en Roi des rois monté sur un cheval blanc (Apocalypse 19).',array['1 Samuel 17.45','Apocalypse 19.11-16']::text[]),
('yahweh-roi','יְהוָה רֹעִי','Yahweh Roï','hébreu','Le Seigneur mon berger','Noms de Dieu','Le Dieu qui conduit, nourrit et protège comme un berger conduit son troupeau. Cœur du Psaume 23.','Jésus dit : « Je suis le bon berger, le bon berger donne sa vie pour ses brebis » (Jean 10.11).',array['Psaume 23.1','Jean 10.11']::text[]),
('go-el','גֹּאֵל','Go''el','hébreu','Le Rédempteur, le proche qui rachète','Noms de Dieu','Le parent le plus proche, chargé de racheter un membre de la famille tombé dans l''esclavage ou la dette (comme Boaz pour Ruth).','Jésus est notre Go''el : il paie de son sang la rançon qui nous arrache à l''esclavage du péché.',array['Ruth 4.14','Job 19.25']::text[]),
('abba','אַבָּא','Abba','araméen','Papa, Père chéri','Noms de Dieu','Mot d''une immense intimité, celui d''un petit enfant. À l''époque de Jésus, il était impensable d''appeler ainsi le Dieu tout-puissant.','Jésus prie « Abba » à Gethsémané, et par l''Esprit nous pouvons crier avec lui « Abba, Père » (Romains 8.15).',array['Marc 14.36','Romains 8.15']::text[]),
('emmanuel','עִמָּנוּ אֵל','Emmanuel','hébreu','Dieu avec nous','Noms de Dieu','Titre prophétique d''Ésaïe : la preuve que Dieu ne nous observe pas de loin, mais vient habiter parmi nous.','Accompli à Noël : « on l''appellera Emmanuel, c''est-à-dire Dieu avec nous » (Matthieu 1.23).',array['Ésaïe 7.14','Matthieu 1.23']::text[]),
('messie','מָשִׁיחַ','Mashiah (Messie)','hébreu','L''Oint','Noms de Dieu','Celui sur qui on a versé l''huile sainte pour le consacrer : le Roi et Sauveur promis depuis l''aube des temps. « Christ » en est la traduction grecque (Christos).','Jésus est le Messie attendu ; « Christ » n''est pas un nom de famille mais ce titre : l''Oint de Dieu.',array['Daniel 9.25','Jean 1.41']::text[]),
('ruach','רוּחַ','Ruach','hébreu','Souffle, vent, Esprit','Le Saint-Esprit','Un même mot pour le souffle, le vent et l''Esprit de Dieu. Le Ruach plane sur les eaux à la création et redonne vie aux ossements desséchés.','Le même souffle qui donne la vie devient le Saint-Esprit répandu à la Pentecôte et habitant le croyant.',array['Genèse 1.2','Ézéchiel 37.9']::text[]),
('pneuma','πνεῦμα','Pneuma','grec','Esprit, souffle','Le Saint-Esprit','Équivalent grec de ruach : le souffle, le vent, l''Esprit. Jésus joue sur ce sens quand il dit que « le vent souffle où il veut ».','Le Pneuma Hagion (Saint-Esprit) est la présence personnelle de Dieu qui vient habiter le croyant à la nouvelle naissance.',array['Jean 3.8','Actes 2.4']::text[]),
('agape','ἀγάπη','Agapè','grec','Amour qui se donne','Le salut et la grâce','L''amour le plus élevé du grec : non l''attirance ou l''amitié, mais l''amour qui décide de se donner pour le bien de l''autre, sans rien attendre en retour. L''amour même de Dieu.','« Dieu est agapè » (1 Jean 4.8) ; la croix en est la démonstration suprême (Romains 5.8). C''est l''amour du chapitre 13 de 1 Corinthiens.',array['1 Corinthiens 13.4-8','1 Jean 4.8']::text[]),
('charis','χάρις','Charis','grec','Grâce, faveur gratuite','Le salut et la grâce','La faveur totalement gratuite offerte à qui ne la mérite pas. Le cœur battant de l''Évangile : on ne la gagne pas, on la reçoit les mains vides.','« C''est par la grâce (charis) que vous êtes sauvés, par le moyen de la foi… c''est un don de Dieu » (Éphésiens 2.8).',array['Éphésiens 2.8-9','Tite 2.11']::text[]),
('hesed','חֶסֶד','Hesed','hébreu','Bonté fidèle, amour d''alliance','Le salut et la grâce','L''amour loyal et tenace de Dieu, sa bonté qui ne lâche pas malgré l''infidélité de l''homme. Se renouvelle « chaque matin ».','Le hesed de Dieu culmine dans le Christ qui reste fidèle quand nous sommes infidèles (2 Timothée 2.13).',array['Lamentations 3.22-23','Psaume 136']::text[]),
('shalom','שָׁלוֹם','Shalom','hébreu','Paix, plénitude','Le salut et la grâce','Bien plus que l''absence de guerre : une paix vibrante, la santé, la prospérité, l''harmonie totale de l''être avec Dieu, les autres et soi-même.','Jésus est le Prince de la paix (Ésaïe 9.5) ; il donne un shalom que le monde ne peut donner.',array['Ésaïe 9.5','Jean 14.27']::text[]),
('hamartia','ἁμαρτία','Hamartia','grec','Péché, manquer la cible','Le salut et la grâce','Terme d''archerie : « manquer la cible », s''égarer. Le péché n''est pas d''abord une liste d''actes, mais l''orgueil de vouloir vivre sans Dieu, qui coupe de la source de la vie.','« Tous ont péché (hamartia) et sont privés de la gloire de Dieu » (Romains 3.23) : d''où le besoin d''un Sauveur.',array['Romains 3.23','Romains 6.23']::text[]),
('metanoia','μετάνοια','Metanoia','grec','Repentance, changement d''esprit','Le salut et la grâce','Non de simples regrets, mais un changement radical de mentalité et de direction : un demi-tour à 180 degrés pour quitter ses voies et revenir vers le Père.','Le premier mot de la prédication de Jésus : « Repentez-vous (metanoeite), car le Royaume des cieux est proche » (Matthieu 4.17).',array['Matthieu 4.17','Actes 2.38']::text[]),
('dikaiosis','δικαίωσις','Dikaiosis','grec','Justification, être déclaré juste','Le salut et la grâce','Terme de tribunal : l''acte par lequel Dieu le Juge, examinant notre dossier accablant, déclare le croyant « acquitté, juste » — parce que Jésus a payé l''amende à sa place.','« Déclarés justes par sa grâce… par la délivrance qui est en Jésus-Christ » (Romains 3.24).',array['Romains 3.24','Romains 5.1']::text[]),
('apolytrosis','ἀπολύτρωσις','Apolytrosis','grec','Rédemption, rachat','Le salut et la grâce','Terme de marché : racheter un esclave en payant une rançon pour lui rendre la liberté.','Jésus donne son sang « en rançon pour une multitude » (Marc 10.45) : notre rédemption.',array['Marc 10.45','Éphésiens 1.7']::text[]),
('euangelion','εὐαγγέλιον','Euangelion','grec','Bonne Nouvelle, Évangile','Le salut et la grâce','L''annonce d''une victoire royale que l''on proclame dans tout le pays. La « bonne nouvelle » : la mort et le mal ont été vaincus par le Roi Jésus à la croix.','L''Évangile même : Christ est mort pour nos péchés et ressuscité (1 Corinthiens 15.3-4).',array['Marc 1.15','1 Corinthiens 15.3-4']::text[]),
('logos','λόγος','Logos','grec','Parole, Verbe','La personne de Christ','La Parole, la raison, le sens. Jean ouvre son Évangile en appelant Jésus « le Logos », qui était au commencement avec Dieu et était Dieu.','« La Parole (Logos) a été faite chair et elle a habité parmi nous » (Jean 1.14) : Jésus lui-même.',array['Jean 1.1','Jean 1.14']::text[]),
('kyrios','κύριος','Kyrios','grec','Seigneur','La personne de Christ','« Seigneur », maître souverain. Dans la Bible grecque, le mot qui traduit le Nom divin. Confesser « Jésus est Kyrios » est la plus ancienne confession chrétienne.','« Si tu confesses de ta bouche que Jésus est Seigneur (Kyrios)… tu seras sauvé » (Romains 10.9).',array['Romains 10.9','Philippiens 2.11']::text[]),
('christos','Χριστός','Christos','grec','Christ, l''Oint','La personne de Christ','Traduction grecque de « Messie » : l''Oint de Dieu, le Roi-Sauveur consacré. Non un nom de famille mais un titre.','« Tu es le Christ (Christos), le Fils du Dieu vivant » : la confession de Pierre (Matthieu 16.16).',array['Matthieu 16.16','Jean 20.31']::text[]),
('amen','אָמֵן','Amen','hébreu','Ainsi soit-il, c''est ferme et vrai','Prière et louange','De la racine qui dit la solidité, la fidélité, la vérité sûre. « Amen » scelle une prière : « oui, c''est vrai, je m''y appuie de tout mon cœur ».','Jésus est appelé « l''Amen, le témoin fidèle » : en lui toutes les promesses de Dieu sont « oui » (2 Corinthiens 1.20).',array['Apocalypse 3.14','2 Corinthiens 1.20']::text[]),
('alleluia','הַלְלוּ יָהּ','Halelou-Yah (Alléluia)','hébreu','Louez le Seigneur','Prière et louange','Contraction de halelou (louez) et Yah (abréviation de YHWH). Le cri de joie suprême de l''âme qui reconnaît la grandeur de Dieu.','Le grand cri du ciel devant le triomphe de l''Agneau : « Alléluia ! car le Seigneur règne » (Apocalypse 19).',array['Psaume 150.6','Apocalypse 19.6']::text[]),
('berith','בְּרִית','Berith','hébreu','Alliance','La foi et l''alliance','Un pacte sacré et solennel scellé par Dieu. L''Ancienne alliance était conditionnelle (la Loi) ; la Nouvelle est un pacte inconditionnel fondé sur la grâce.','« Cette coupe est la nouvelle alliance (berith) en mon sang » (Luc 22.20) : scellée à la croix.',array['Jérémie 31.33','Luc 22.20']::text[]),
('pistis','πίστις','Pistis','grec','Foi, confiance, fidélité','La foi et l''alliance','Non une adhésion intellectuelle vague, mais une confiance vitale et une loyauté envers une personne : s''appuyer entièrement sur Jésus et ses promesses.','« Le juste vivra par la foi (pistis) » (Romains 1.17) : on est sauvé en s''appuyant sur Christ, non sur ses œuvres.',array['Hébreux 11.1','Romains 1.17']::text[]),
('shema','שְׁמַע','Shema','hébreu','Écoute','La foi et l''alliance','Le premier mot de la grande confession d''Israël : « Écoute, Israël, le Seigneur notre Dieu est le seul Seigneur. » Écouter, dans la Bible, c''est écouter pour obéir.','Jésus cite le Shema comme le plus grand commandement : aimer Dieu de tout son cœur (Marc 12.29-30).',array['Deutéronome 6.4-5','Marc 12.29-30']::text[]),
('koinonia','κοινωνία','Koinônia','grec','Communion, partage','L''Église et la vie chrétienne','La mise en commun, la communion profonde : partage des biens, de la foi, de la vie. Ce qui liait la première Église.','La communion (koinônia) avec le Père et le Fils, et des croyants entre eux, par l''Esprit (1 Jean 1.3).',array['Actes 2.42','1 Jean 1.3']::text[]),
('ekklesia','ἐκκλησία','Ekklêsia','grec','Église, assemblée des appelés','L''Église et la vie chrétienne','Litt. « ceux qui sont appelés hors ». Non un bâtiment, mais l''assemblée de tous ceux que Dieu appelle à lui.','« Sur cette pierre je bâtirai mon Église (ekklêsia) » (Matthieu 16.18) : le peuple que Christ se construit.',array['Matthieu 16.18','Éphésiens 1.22-23']::text[]),
('baptizo','βαπτίζω','Baptizô','grec','Plonger, immerger','L''Église et la vie chrétienne','« Plonger, immerger ». Le baptême dit une mort et une résurrection : on descend sous l''eau avec Christ, on remonte à une vie nouvelle.','« Ensevelis avec lui par le baptême… ressuscités avec lui » (Colossiens 2.12).',array['Romains 6.4','Colossiens 2.12']::text[]),
('doxa','δόξα','Doxa','grec','Gloire, poids, éclat','Adoration','L''éclat, le poids, la splendeur de Dieu. Le kavod hébreu en est l''équivalent : la présence « lourde » et rayonnante de Dieu.','En Christ nous contemplons « la gloire (doxa) de Dieu » ; il est le reflet de sa gloire (Hébreux 1.3).',array['Jean 1.14','Hébreux 1.3']::text[]),
('kavod','כָּבוֹד','Kavod','hébreu','Gloire, poids','Adoration','La « lourdeur », le poids, l''importance. La gloire de Dieu, c''est le poids écrasant de sa présence qui remplissait le Temple.','La gloire qui remplissait le Temple vient habiter en personne dans le Christ, « Emmanuel ».',array['Exode 40.34','Ésaïe 6.3']::text[]),
('hagios','ἅγιος','Hagios','grec','Saint, mis à part','Adoration','« Saint » : mis à part, autre, pur. Dieu est trois fois saint. Les croyants sont appelés « saints » car mis à part pour lui.','Christ nous « sanctifie » : mis à part par son sang pour appartenir à Dieu (Hébreux 10.10).',array['Ésaïe 6.3','1 Pierre 1.16']::text[]),
('sarx','σάρξ','Sarx','grec','La chair','La création et l''homme','« La chair » : non seulement le corps, mais la nature humaine livrée à elle-même, tournée vers ses désirs plutôt que vers Dieu.','« La Parole est devenue chair (sarx) » (Jean 1.14) : Dieu épouse notre humanité pour la sauver.',array['Jean 1.14','Galates 5.16']::text[]),
('nephesh','נֶפֶשׁ','Nephesh','hébreu','Âme, être vivant, gorge','La création et l''homme','Le souffle vital, l''être vivant tout entier, parfois « la gorge » assoiffée. L''homme ne « possède » pas une âme : il est une nephesh vivante.','« Mon âme (nephesh) a soif de Dieu » (Psaume 42) : soif que seul étanche le Christ, eau vive (Jean 4).',array['Genèse 2.7','Psaume 42.2-3']::text[]),
('shabbat','שַׁבָּת','Shabbat','hébreu','Repos, cessation','La foi et l''alliance','« Cesser, s''arrêter ». Le septième jour où Dieu se repose et invite l''homme à se reposer en lui, à ne pas se sauver par ses œuvres.','Jésus est le vrai repos : « Venez à moi… et je vous donnerai le repos » (Matthieu 11.28) ; il est Seigneur du sabbat.',array['Genèse 2.2-3','Matthieu 11.28']::text[])
on conflict (slug) do update set
  term=excluded.term, translit=excluded.translit, lang=excluded.lang, gloss=excluded.gloss,
  theme=excluded.theme, sense=excluded.sense, christ=excluded.christ, refs=excluded.refs;
