-- Enrichissement de bible_words : les Noms de Dieu du "Livret Complet des
-- Noms Hebreux de Dieu" qui manquaient encore a la base /mots.
-- Meme table et meme schema que 0016_bible_words.sql.

insert into bible_words (slug, term, translit, lang, gloss, theme, sense, christ, refs) values
('yahweh-tsidkenu','יְהוָה צִדְקֵנוּ','Yahweh Tsidkenu','hébreu','Le Seigneur notre justice','Noms de Dieu','Non pas la justice que nous produisons, mais celle que Dieu donne. Notre statut de « juste » ne vient pas de nos efforts : il nous est accordé par lui seul.','« Il a fait de lui notre justice » : en Christ, sa justice nous est imputée, cœur de la justification par la foi.',array['Jérémie 23.6','2 Corinthiens 5.21']::text[]),
('yahweh-shammah','יְהוָה שָׁמָּה','Yahweh Shammah','hébreu','Le Seigneur est là','Noms de Dieu','Un simple adverbe de lieu (« là ») devenu nom de Dieu : sa présence localisée, affirmée, irréfutable, jusque dans la ville restaurée de la vision d''Ézéchiel.','« Je suis avec vous tous les jours » : la présence de Dieu habite désormais son peuple par l''Esprit.',array['Ézéchiel 48.35','Matthieu 28.20']::text[]),
('yahweh-meqaddishkem','יְהוָה מְקַדִּשְׁכֶם','Yahweh Meqaddishkem','hébreu','Le Seigneur qui vous sanctifie','Noms de Dieu','De qadash : mettre à part, séparer pour Dieu. La sainteté est d''abord relationnelle : être mis à part pour lui, lui appartenir, avant d''être une qualité morale.','Christ nous sanctifie par son sacrifice et nous met à part pour Dieu, une fois pour toutes.',array['Lévitique 20.8','Hébreux 10.10']::text[]),
('el-elyon','אֵל עֶלְיוֹן','El Elyon','hébreu','Dieu Très-Haut','Noms de Dieu','De alah : monter, s''élever. Le Dieu du plus haut degré de hauteur, au-dessus de tout trône, de toute autorité, de toute puissance cosmique ou humaine. Invoqué par Melchisédek.','Christ est élevé au-dessus de tout nom, assis à la droite du Très-Haut (Éphésiens 1.20-21).',array['Genèse 14.18-20','Éphésiens 1.20-21']::text[]),
('el-roi','אֵל רֳאִי','El Roï','hébreu','Le Dieu qui me voit','Noms de Dieu','Le nom que donne Agar, esclave fugitive et oubliée de tous. Même la personne rejetée est vue par Dieu ; il connaît sa détresse et vient à elle.','Jésus voit et appelle les oubliés, les exclus, les invisibles, et s''arrête pour eux.',array['Genèse 16.13','Luc 19.5']::text[]),
('el-olam','אֵל עוֹלָם','El Olam','hébreu','Le Dieu éternel','Noms de Dieu','Le Dieu de toujours, immuable et fidèle, sans défaillance à travers les générations. Une ancre stable quand tout change et passe.','« Jésus-Christ est le même hier, aujourd''hui et éternellement » (Hébreux 13.8).',array['Genèse 21.33','Hébreux 13.8']::text[]),
('el-gibbor','אֵל גִּבּוֹר','El Gibbor','hébreu','Dieu vaillant, le Héros','Noms de Dieu','Le Champion qui descend combattre pour les siens. Non un Dieu spectateur, mais un guerrier qui se lève pour défendre son peuple.','Ésaïe donne ce titre à l''enfant qui naîtra : « Dieu fort (El Gibbor), Prince de la paix » (Ésaïe 9.5).',array['Ésaïe 9.5','Sophonie 3.17']::text[]),
('el-channun','אֵל חַנּוּן','El Channoun','hébreu','Dieu gracieux','Noms de Dieu','La grâce abondante et généreuse de Dieu, penché avec faveur sur celui qui ne mérite rien. La bonté imméritée comme trait même de son caractère.','En Christ, cette grâce prend chair : « pleine de grâce et de vérité » (Jean 1.14).',array['Exode 34.6','Jean 1.14']::text[]),
('tsur','צוּר','Tsour','hébreu','Le Rocher','Noms de Dieu','Le fondement inébranlable. Tout peut vaciller — travail, santé, relations, économies — mais bâtir sur le Rocher, c''est ne pas être emporté quand viennent les tempêtes.','« Ce Rocher, c''était Christ » (1 Corinthiens 10.4) : le seul fondement qui ne peut être ébranlé.',array['Deutéronome 32.4','1 Corinthiens 10.4']::text[])
on conflict (slug) do update set
  term=excluded.term, translit=excluded.translit, lang=excluded.lang, gloss=excluded.gloss,
  theme=excluded.theme, sense=excluded.sense, christ=excluded.christ, refs=excluded.refs;
